source 'https://github.com/CocoaPods/Specs.git'

target 'NBReorderTableView', :exclusive => true do
  pod "NBReorderTableView", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "NBReorderTableView", :path => "../"

  
end
